### ISSUE TITLE
[contract] applying factory pattern 

### ISSUE THREAD

**Issue by bbabi0901** [codestates-beb/BEB-07-final-CDS#167]
Storage contract의 변수

```Solidity
contract Swap is PriceConsumer, Ownable {
  using SafeMath for uint256;

  enum Status {
    inactive,
    pending,
    active,
    claimed,
    expired
  }
  Status status;

  address buyer;
  address seller;

  uint256 initAssetPrice;
  uint256 claimPrice;
  uint256 liquidationPrice;
  uint256 premium;
  uint256 sellerDeposit;

  uint256 interval;
  uint32 rounds;

...

}
```

Logic contract의 변수

```Solidity
Swap private swap;

struct Deposit {
  uint256 deposit;
  bool isPaid;
}

mapping(uint256 => Swap) private _swaps;

mapping(uint256 => uint256) private _nextPayDate;

mapping(uint256 => Deposit[2]) private _deposits;
```

**Comment by bbabi0901** [comment]
컨트랙트 메소드 변경점

```Solidity
// Swap contract address 반환
function getSwap(uint256 swapId) public view returns (Swap) {
  return _swaps[swapId];
}

// [{initAssetPrice}, {claimPrice}, {liquidationPrice}, {premium}, {sellerDeposit}]의 배열 반환
function getPrices(uint256 swapId) public view returns (uint256[5] memory) {
  return _swaps[swapId].getPrices();
}

// buyerrk claim시 받을 수 있는 reward 반환
function getClaimReward(uint256 swapId) public view returns (uint256) {
  uint256 currPrice = getPriceFromOracle();
  if (getSwap(swapId).claimPrice() < currPrice) {
    return 0;
  }
  return
    getSellerDeposit(swapId).calcClaimReward(
      getSwap(swapId).liquidationPrice(),
      getSwap(swapId).initAssetPrice(),
      currPrice
    );
}

// contract에 설정된 premium 반환
function getPremium(uint256 swapId) public view returns (uint256) {
  return _swaps[swapId].premium();
}

// contract에 설정된 sellerDeposit 반환
function getSellerDeposit(uint256 swapId) public view returns (uint256) {
  return _swaps[swapId].sellerDeposit();
}

// status 반환 => 0: inactive, 1: pending, 2: active, 3: claimed, 4: expired
function getStatus(uint256 swapId) public view returns (Swap.Status) {
  return _swaps[swapId].status();
}

// 남은 round 수 반환
function getRounds(uint256 swapId) public view returns (uint32) {
  return _swaps[swapId].rounds();
}

// 설정된 주기 반환
function getInterval(uint256 swapId) public view returns (uint256) {
  return _swaps[swapId].interval();
}

// buyer address 반환
function getBuyer(uint256 swapId) public view returns (address) {
  return _swaps[swapId].getBuyer();
}

// seller address 반환
function getSeller(uint256 swapId) public view returns (address) {
  return _swaps[swapId].getSeller();
}

// 납부된 buyer/seller의 deposit data 배열 반환 => [{deposit, isPaid} : buyer, {deposit, isPaid} : seller] 
function getDeposits(uint256 swapId) public view returns (Deposit[2] memory) {
  return _deposits[swapId];
}
```

**Comment by bbabi0901** [comment]
https://medium.com/@aiden.p/%EC%97%85%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%8D%94%EB%B8%94-%EC%BB%A8%ED%8A%B8%EB%9E%99%ED%8A%B8-%EC%94%A8-%EB%A6%AC%EC%A6%88-part-1-%EC%97%85%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%8D%94%EB%B8%94-%EC%BB%A8%ED%8A%B8%EB%9E%99%ED%8A%B8%EB%9E%80-b433225ebf58

https://deeprnd.medium.com/solidity-gas-optimisation-83c75170f534

**Comment by atoye1** [comment]
팩토리패턴이 적용된 예시에서도 CDS 컨트랙트는 한개만 배포된걸 사용하는가요?
createSwap을 호출하면 새로운 CDS가 생성되는게 아니라 Swap 컨트랙트가 새롭게 생성되는건가요?

아래에 제가 이해한게 맞을까요?

1. 사용자는 CDS에 있는 createSwap 메서드를 호출해서 
2. swap handler에 있는 _createSwap을 호출한다.
3. swap handler는 Swap.sol에 컨트랙트를 바탕으로 새로운 컨트랙트를 _createSwap이 호출될때마다 생성한다.
4. 매번 생성되는 컨트랙트의 주소는 SwapHandler의 맵핑에 저장된다.
5. CDS 컨트랙트의 이벤트인 CreateSwap에서 얻는 swapId를 얻는다.
6. 해당 swapId로 SwapHandler의 getSwap(swapId) 호출을 통해 개별 Swap 컨트랙트의 CA를 받을 수 있다.

그러면 컨트랙트 배포시 항상 SwapHandler의 배포된 주소를 알고 있어야 블록리스너에서 web3 call이 가능할것 같은데 migrations에는 반영이 되어있지 않아서 혼란스럽습니다.

**Comment by atoye1** [comment]
아차 CDS가 swapHandler를 상속받는군요..  그러면 따로 SwapHandler를 배포하지 않아도 상관없겠네요

**Comment by bbabi0901** [comment]
CDS(+SwapHandler)는 하나의 컨트랙트만 사용하는게 맞습니다.
1~6까지 말씀하신게 정확합니다.

Swap 컨트랙트 주소를 통해서 해당 컨트랙트의 변수(initAssetPrice, claimPrice 등)에 접근할 수도 있지만,
SwapHandler의 swapId를 인자로 하는 getPrices등의 메소드를 통해 Swap 컨트랙트의 변수에 접근할 수도 있습니다.

**Comment by atoye1** [comment]
CDS에서 외부로 노출되는 인터페이스를 크게 변경하지 않고도 팩토리 패턴이 적용되었다니 놀랍기도 하면서도 몇 가지 추가적으로 의문이 듭니다.

팩토리 패턴이 적용되어서 어떤점이 개선되었는지 궁금합니다.

1. 지난번 용량 문제가 개선되는건가요?
2. 가스비가 개선되는 건가요?
3. 아니면 팩토리 패턴을 적용함으로 인해서 추가로 구현할 수 있는 기능상의 이점이 생기는 건가요?

사실 회의때 언급하셨던것 같던데... 제가 기억을 잘 못하겠어요 😿

**Comment by bbabi0901** [comment]
1. 용량 문제는 확실히 개선되었습니다.
실제로 용량 문제로 추가하지 못했던 기능이(seller의 cancel, buyer의 accept) 추가되었음에도 더이상 해당 문제는 발생하지 않았습니다.
기존의 struct 규모로 기록하던 swap들이 하나의 address 단위로 줄어듦에 따라 해결된 듯 합니다.

2. 가스비 부분은 사실 제가 체크해봤어야했는데 깜빡해서 잘 모르겠네요.

3.  일단 제가 구현하면서 기대한 것은 협상의 구현이 쉬워지고, Swap에 더 다양한 변화를 줄 수 있을 것 같습니다.
예컨데, Swap에 buyer, seller를 기록함으로서 계약의 양도도 가능해지지 않을까 싶네요.
또한, CDS 컨트랙트에 속한 구조체가 아닌 별개의 컨트랙트로 존재한다는 건 사용자에게 완전히 다른 의미를 줄 수 있을 것 같습니다.
Swap 컨트랙트에 메소드와 buyer, seller를 확인하는 검증기능만 추가해둔다면, 저희를 거치지 않고도 사용자 본인들이 접근, 변경할 수 있겠네요
