### ISSUE TITLE
[contract] Swap에서 remainRound, totalRound 두 가지 변수 관리

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/BEB-07-final-CDS#193]
현재 Swap에서 `uint32 public rounds;` 형태로 현재 남은 라운드의 스냅샷만을 제공하고 있습니다.

블록리스너에서 예전에 생성된 스왑의 총 라운드를 DB에 저장하려고 할때 최초 계약시 총 라운드가 얼마였는지 파악하지 못하는
문제가 생깁니다.

혹시 현재 컨트랙트에서 조회할수 있는 방법이 있을까요? 만약 없다면 remainRound, totalRound 두 가지 형태로 round 변수를 관리하고, 조회하는 getter 메서드도 구현해주셨으면 좋겠습니다.

**Comment by atoye1** [comment]
회의에서 결정했던 컨트랙트 변경없이 진행하는 방식의 구현이 복잡하고 매번 DB트랜잭션을 발생시켜서 컨트랙트쪽에서 크게 부담이 안되면 createSwap 이벤트에 total Premium Rounds를 같이 넣어주시면 좋겠습니다.

**Comment by bbabi0901** [comment]
이벤트 말고 처음 말씀하신대로 별도의 변수로 저장하고 getter 메서드로 구현해드리면 어떨까요?

**Comment by atoye1** [comment]
그 방법도 괜찮습니다.

**Comment by bbabi0901** [comment]
곧 반영해서 병합하겠습니다 
이하는 추가되는 메서드입니다
```Solidity
function getTotalRounds(uint256 swapId) public view returns (uint32) {
  return _swaps[swapId].totalRounds();
}
```
