### ISSUE TITLE
[server]swagger연동을 통한 api문서 작성

### ISSUE THREAD

**Issue by NotoriousHong** [codestates-beb/BEB-07-final-CDS#227]

**Comment by atoye1** [comment]
아래의 URI로 접속하면 api문서를 볼 수 있습니다.
이슈는 닫지만 혹시 버그있으면 댓글 부탁합니다.

https://nodeauction.42msnsnsfoav6.ap-northeast-2.cs.amazonlightsail.com/api-docs/
