### ISSUE TITLE
[server]mypage POST router

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/BEB-07-final-CDS#248]
`POST /users/my`로 회원정보 등록을 합니다.

req.body는 다음과 같습니다.
email과 nickname 둘중 하나는 입력해야 올바른 응답을 줍니다.
```
{
  "email":<valid email>,
  "nickname":<maxlength 50>,
}
```

nickname 기본값은 아래와 같이 anonymous_\<5 hash\>로 저장됩니다.

![Image](https://user-images.githubusercontent.com/47937914/217409509-b3c04309-cc9c-4429-b883-e87993c17fba.png)

**Comment by atoye1** [comment]
여기로 닉네임, 이메일 수정 요청하시면 됩니다.
리셋되는 버그도 수정되었습니다.

현재 제가 사용하는 계정에는 이메일이 들어가 있으므로,

`0x49a1bcc1962d02fd83bc72e1f0ffccf48b4a476f` 기준으로 구현하시면 편하실겁니다.

![Image](https://user-images.githubusercontent.com/47937914/217414352-82e68a69-4a8a-4737-90a0-b17489ca5107.png)

**Comment by NotoriousHong** [comment]
withCredentials 문제 반영후 post동작 전부 잘 작동됩니다.

그리고 post요청 후에 입력한 데이터도 정장적으로 return받고 있습니다.
