### ISSUE TITLE
[server]메일링 서비스 제공

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/BEB-07-final-CDS#253]
이메일을 등록한 유저에 한해서
메일링 서비스를 제공합니다.

<현재 구현됨>

1. 최초 이메일 등록시
2. 이메일 변경시
3. 로그인시

<구현 예정>

1. 본인과 관련된 스왑 발생시
2. 본인과 관련된 스왑에 트랜잭션 발생시

**Comment by atoye1** [comment]
현재 버그가 수정되어 이메일이 등록된(제가 수동으로 DB에서 넣은)
두훈님의 경우 로그인시 로그인 이메일을 수신할 수 있습니다.
(안오면 스팸함을 확인해주세요)

**Comment by Duhoon** [comment]
<img width="1192" alt="스크린샷 2023-02-08 오후 2 23 46" src="https://user-images.githubusercontent.com/18072469/217441906-d8abbc2b-7bd5-44f0-bd65-7c0988ea87f8.png">

로그인 시 메일 오는 것 확인했습니다.

**Comment by atoye1** [comment]
로그인시, 이메일 등록시 이메일을 받을 수 있습니다.
닉네임을 변경했을때도 이메일이 등록되었다는 메일이 발신되는 버그가 있습니다.
추후 수정예정

**Comment by atoye1** [comment]
create, accept 등에도 메일링 서비스를 제공할 예정이지만, 우선순위가 낮으므로 잠정적으로 이슈 닫습니다.

**Comment by atoye1** [comment]
이메일이 등록된 사용자가 create Swap할시에 아래와 같은 알림 메일을 보내줍니다.
```
Dear donghun seol
 You just triggered Create Event on 1676189109
 swapId: 34
 txHash : 0xc38fa8b92539676c7c75fa489793878b8cdd8d008569911310bba928a2d9f0bc
 swapInfo : https://dubnjq842z47s.cloudfront.net/swaps/34
 txInfo : http://snowdelver.iptime.org:48080/transactions/0xc38fa8b92539676c7c75fa489793878b8cdd8d008569911310bba928a2d9f0bc
 
```
accept시에 알람을 주는 기능까지만 추가구현하겠습니다.

**Comment by atoye1** [comment]
주요 이벤트인 Accept, Claim 시에도 아래와 같이 이메일 알람이 잘 전송됩니다.


![Image](https://user-images.githubusercontent.com/47937914/218312793-71b70692-a514-4c60-87cb-bbe586e08f35.png)
