### ISSUE TITLE
[contract] migtration시 fusd 토큰 지급 관련 오류가 발생합니다

### ISSUE THREAD

**Issue by bbabi0901** [codestates-beb/BEB-07-final-CDS#260]
`Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)`

```JavaScript
const defaultTokenFaucet = 1e18;
...
const fusd = await FUSD.deployed();
await fusd.transfer(accounts[1], defaultTokenFaucet, { from: accounts[0] });
await fusd.transfer(accounts[2], defaultTokenFaucet, { from: accounts[0] });
await fusd.transfer(accounts[3], defaultTokenFaucet, { from: accounts[0] });
await fusd.transfer(accounts[4], defaultTokenFaucet, { from: accounts[0] });
```

**Comment by atoye1** [comment]
혹시
1e18을 `BigInt(1e18)` 하거나
스트링으로 '10000000000000000000000000000000' 넣으면 안될까요?

**Comment by bbabi0901** [comment]
```JavaScript
const defaultTokenFaucet = 10 ** 8;
```
`defaultTokenFaucet`에 대한 설정을 위와 같이 했을 때는 오류가 발생하지 않았습니다.

**Comment by bbabi0901** [comment]
> 혹시 1e18을 `BigInt(1e18)` 하거나 스트링으로 '10000000000000000000000000000000' 넣으면 안될까요?
`10 ** 18`은  적용을 해봤는데 같은 오류가 발생했고 말씀하신 방법을 차례대로 시도해보겠습니다

**Comment by bbabi0901** [comment]
`StatusError: Transaction: 0xd5bca989c9edd1ef42d585fdad62443759d5895f01d40df1891c7feeec758781 exited with an error (status 0). Reason given: ERC20: transfer amount exceeds balance.`

**Comment by bbabi0901** [comment]
이번에는 밸런스 오류가 나네요

**Comment by atoye1** [comment]
단위 처리가 까다로워서 그런데

` _mint(msg.sender, 100 * 10 ** uint256(decimals()));`
요 수량이 문제인것 같아요

**Comment by atoye1** [comment]
10000개 발행하려면 혹시 10000 * 1e18하면 되지 않나요?

https://solidity-by-example.org/ether-units/

**Comment by bbabi0901** [comment]
> 단위 처리가 까다로워서 그런데
> 
> ` _mint(msg.sender, 100 * 10 ** uint256(decimals()));` 요 수량이 문제인것 같아요

저도 이 단계에서의 처리때문에 문제가 발생하는 듯 합니다.
하나 궁금한 것은 기존에 `10 ** 8`씩 배급했을 때 메타마스크에서 표기되는 토큰 수량이 조금 이해가 안가네요

**Comment by atoye1** [comment]
0.0000000001

제 생각엔 현재소수점 뒤에 영이 10개 있는데
기본은 decimal이 18이니까 10 ** 8 해서 그렇게 차이가 나는거 같아요.

**Comment by atoye1** [comment]
데시멀을 0으로 바꾸고 싶으면 erc20 생성자 안에서 이걸 호출하면
마음대로 바꿀수 있을것 같아요

![image](https://user-images.githubusercontent.com/47937914/217448534-7a2b65d2-6fcf-4d32-b53f-608018733270.png)

https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#ERC20-_setupDecimals-uint8-

**Comment by atoye1** [comment]
현재 FUSD 토큰 지급 잘 되므로 닫습니다.
