### ISSUE TITLE
[contract] Getter 메서드 사용 여부 공유

### ISSUE THREAD

**Issue by Duhoon** [codestates-beb/BEB-07-final-CDS#266]
서버와 클라이언트에서 사용하고 있는 CDS 컨트랙트의 Getter 메서드를 공유하여
CDS의 다이어트를 성공시킵니다.

**Comment by Duhoon** [comment]
현재 Accept 페이지에서 getPremium, getSellerDeposit 를 이용하고 있습니다.
아마 추후에 getNextPayDate까지는 이용하게 될 것 같습니다.

**Comment by atoye1** [comment]
getSwap()
getRounds() 

현재 위 두개 사용중입니다.

**Comment by bbabi0901** [comment]
네 확인했습니다
두훈님 말씀하신 getNextPayDate는 public variable인 nextPayDate로의 접근으로 대체할 수 있을 것 같습니다
ex) methods.nextPayDate(swapId).call()
그 외에 정리해도 무방한 getter 메서드는 정리토록 하겠습니다.

**Comment by atoye1** [comment]
Swap.sol 에 getPrices(), getBuyer(), getSeller() 도 사용중입니다.

**Comment by bbabi0901** [comment]
동일한 메서드들이 CDS의 SwapHandler.sol에도 있는데,
Swap 컨트랙트에 호출하시는 건가요? 아니면 CDS 컨트랙트에 호출하시는 건가요?

**Comment by atoye1** [comment]
CDS에 있는걸 발견을 못해서 Swap 컨트랙트에다 호출하고 있습니다.

**Comment by bbabi0901** [comment]
그러면 CDS 컨트랙트의 getTotalRounds()만 사용처가 없어보이네요 
감사합니다
