### ISSUE TITLE
[client] block Explorer 연결메뉴 신설

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/BEB-07-final-CDS#276]
![Image](https://user-images.githubusercontent.com/47937914/217705009-841e6266-ca8a-4770-ae53-ec3752cd0670.png)

메뉴 상단에 block explorer(가칭) 등의 제목으로 클릭시
아래로 연결되는 버튼 요청합니다.
http://snowdelver.iptime.org:48080/dashboard

아울러 그라파나도 메뉴 상단에 node explorer 등의 제목으로 메뉴 상단에 배치했으면 합니다.

포트폴리오를 보는 사람의 입장에서 해당 기능에 쉽게 접근할 수 있게 하기 위해서 요청합니다.

**Comment by Duhoon** [comment]
@NotoriousHong 그라파나 연동되고 있는 슬라이드와 별도로
헤더에 <a> 태그 써서 연결되게하면 될 것 같습니다.
헤더 디자인에 문제가 없는 것이 확인되면 제가 작업 진행하도록 하겠습니다.

**Comment by atoye1** [comment]
Block(chain) Explorer
Node Monitor

식으로 명명해주시면 좋겠습니다.

**Comment by Duhoon** [comment]
요청 구현 완료되어 이슈 닫습니다!
