### ISSUE TITLE
[server]Faucet api 제공

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/BEB-07-final-CDS#297]
GET /faucet/ether (login required)
GET /faucet/token (login required)

**Comment by atoye1** [comment]
최초 지갑연결시 자동으로 웰컴 이더와 토큰을 지급하도록 백엔드단에서 다 처리하겠습니다.
해당 라우터를 사용하지 않고, 따라서 버튼도 구현하지 않으셔도 됩니다.
이슈 닫습니다.

**Comment by atoye1** [comment]
최초 지갑연결시 웰컴기프트로 5ETH, 500,000 FUSD가 제공됩니다.
제 계정으로는 테스트가 잘 되는데, 다른분들도 한번 테스트 해보고 피드백 주시길 요청합니다.

**Comment by Duhoon** [comment]
완전히 새로운 계정에 들어오는 것 확인되었습니다.
