### ISSUE TITLE
[contract]가나슈에서 체인링크 사용하기

### ISSUE THREAD

**Issue by atoye1** [codestates-beb/BEB-07-final-CDS#5]
체인링크를 가나슈에서 사용하기 위해서 기존의 네트워크를 포크해야 합니다.

`ganache-cli --fork https://goerli.infura.io/v3/<api key> -d <mnemonics>`
위의 명령으로 고얼리 네트워크를 포크한 가나슈 네트워크를 생성가능합니다.
아래를 참고했습니다.
https://ethereum.stackexchange.com/questions/91695/how-to-use-chainlink-with-truffle-ganache

하지만 해당 네트워크에서 새로운 컨트랙트 배포시 아래와 같은 에러가 발생했습니다.
`<rejected> CodedError: Given input "NaN" is not a number.`

아래를 참고해서 하드햇 네트워크를 사용해서 문제점 해결을 시도해보고 있습니다.
https://stackoverflow.com/questions/72241463/can-not-deploy-my-contract-on-ganache-cli-using-eth-mainnet-fork

**Comment by atoye1** [comment]
하드햇 노드를 사용한 로컬네트워크에서 goerli 네트워크 포크한 후 체인링크를 호출하는데는 성공했습니다.
하지만 포크했을때의 '상태'가 스냅샷으로 저장되므로 비트의 값이 고정되버리는 문제가 생겼습니다.
(체인링크에서 동적으로 갱신되는 값이 포크한 시점으로 고정되어버림)

이 때문에 개발단계에서는 체인링크를 사용하지 않는 방향으로 선회하고자 합니다. 
이를 위해 체인링크처럼 데이터를 제공하는 커스텀 오라클 컨트랙트 구현했습니다.
이 컨트랙트를 활용하면 간단하게 값을 세팅하고, 세팅한 값을 불러올 수 있으므로
우리 테스트 목적에 잘 맞다 생각합니다.

깃헙이 아직 정리되지 않아서 일단 여기에 코드를 올립니다.

오라클
getPrice, setPrice를 호출가능합니다.
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

contract PriceOracleMock {
    uint256 price;

    constructor(uint256 _initialPrice) {
       price = _initialPrice;
    }

    function getPrice() public view returns (uint256) {
        return price;
    }

    function setPrice(uint256 _price) public returns (uint256) {
        price = _price; 
        return price;
    }
}

```

오라클을 활용하는 예시
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

import "./priceOracleMock.sol";

contract PriceConsumer {
    PriceOracleMock private priceOracle;


    constructor() {}

    function getPriceFromOracle() public view returns (uint256) {
        uint256 result = priceOracle.getPrice();
        return result;
    }

    function setOracle(address _priceOracleAddress) public returns (bool) {
        require(_priceOracleAddress != address(0x0), 'Invalid address');
        priceOracle = PriceOracleMock(_priceOracleAddress);
        return true;
    }
}
```

**Comment by bbabi0901** [comment]
priceOracle = PriceOracleMock(_priceOracleAddress); 부분에서 _initialPrice가 들어가야 하지 않나요?

**Comment by atoye1** [comment]
_initialPrice 변수는 오라클 생성자에 들어가는 변수입니다.
따라서 오라클을 생성할때 즉, 컨트랙트를 배포할때만 들어갑니다.

언급하신 부분은 이미 배포된 오라클 컨트랙트를 컨슈머 안에서 호출하기 위해서 주소를 지정해주는 부분이라 _initialPrice가 필요 없습니다.
