### ISSUE TITLE
[contract]Remix활용하여 Goerli 네트워크에서 체인링크 테스트

### ISSUE THREAD

**Issue by bbabi0901** [codestates-beb/BEB-07-final-CDS#6]
https://docs.chain.link/getting-started/consuming-data-feeds/

**Comment by atoye1** [comment]
저도 체인링크에 있는 예제로 가격은 잘 불러와지는데
가격이 0.5%이상 변동하지 않는 이상 갱신 인터벌이 한시간이네요.

**Comment by bbabi0901** [comment]
그럼 0.5% 이상의 변동에서는 인터벌이 짧아진다는 말씀이시죠?
갱신 주기가 달라질 수도 있군요

**Comment by atoye1** [comment]
네 0.5% 이상 변하면 즉각 반영되는 것 같아요.

체인링크의 기준에 맞추고, 쉽게 구현하려면
가격이 최대 한시간동안은 안정적으로 정해지므로
제안할때와 수락할때 모두 가격을 실시간으로 조회해서 양자의 가격이 다른 경우 
자동으로 계약을 폐기하거나, 카운터오퍼를 자동으로 보내주는 등의 로직이 생각나네요

**Comment by bbabi0901** [comment]
그러면 makeSwap시와 acceptSwap시의 가격을 모두 기록할 필요가 있겠네요

양 시점의 가격차이가 일정 범위 내라면(ex 0.5%),
카운터오퍼 생략하고 바로 체결, 범위 밖이면 폐기하는 방식도 생각해볼 수 있겠습니다

**Comment by atoye1** [comment]
아래 디스커션에서 시간을 갖고 계속 논의해보면 좋겠습니다.
https://github.com/codestates-beb/BEB-07-final-CDS/discussions/8
