### ISSUE TITLE
[contract] CDS 보상금 정산

### ISSUE THREAD

**Issue by Duhoon** [codestates-beb/BEB-07-final-CDS#93]
CDS 보상금 정산 관련하여 사용이 필요한 변수들, 그리고 보상금 값을 구하는 식에 대한 논의가 필요합니다.

**Comment by Duhoon** [comment]
**[Discord 의견]**
```
claim시 buyer가 받아가는 claimDeposit은 다음과 같이 계산했습니다.

1. 현재 가격이 설정된 liquidationPrice 이하일 경우
  claimDeposit = liquidationPrice
2. 현재 가격이 설정된 claimPrice과 liquidationPrice 사이의 값을 가질 경우
  2-1. seller의 담보금, 청산 가격, Swap 체결 당시 비트 가격으로부터 비트 개수 역산
    numOfAsset = sellerDeposit / (initialPrice - liquidationPrice)
  2-2. 비트 개수를 참조하여 claimDeposit 계산
    claimDeposit = numOfAsset * (initialPrice - currentPrice)

이후 seller는 sellerDeposit - claimDeposit 만큼 회수하게 됩니다.

```

**Comment by Duhoon** [comment]
numOfAsset을 구하는 식은 문제가 없어 보입니다.
다만 추후 회의에서도 얘기를 나누겠지만 numOfAsset 등 필요한 모든 변수들을 우선 컨트랙트에 저장하고 사용하자고 제안을 드릴 생각입니다.
그렇다면 numOfAsset을 정산하는 시점에서 따로 구할 필요 없이 Swap 객체에서 꺼내 쓰시기만 하면 될 것 같습니다.

그리고 `claimDeposit` 변수명을 보상금과 관련한 `claimReward` 나 `claimPaid` 같은 변수명으로 변경하여 보증금이라는 의미와는 차별을 두면 좋을 것 같습니다.

**Comment by atoye1** [comment]
저도 두훈님이랑 같은 의견으로 식은 문제가 없는것 같구요
Swap 구조체에 numOfAsset변수는 일단 추가해놓으면 다른 기능 개발시에 유용할 수 있으니 추가하면 좋겠습니다.
변수명도 `deposit`에서 `compensation`로 바꾸면 좋겠다는 의견입니다.

여러가지 동의어를 찾아봤는데

채권 bond
보험금 insuarance money
보상 reward, compensation
담보 collateral

아래 캡쳐와 같이 구글 검색결과와 같이 `compensation`이 우리 상황에 적절한 단어인 것으로 보입니다.
![image](https://user-images.githubusercontent.com/47937914/214769903-3721a442-818b-4ab2-b2f1-a34303c706f9.png)

**Comment by bbabi0901** [comment]
`claimDeposit` 변수명은 일단은 `claimReward`로 맞춰 놓고 얘기되는 방향에 맞춰 놓겠습니다.
numOfAsset역시 회의의 결정사항에 따라 정해지겠지만 일단 구조체에 추가하는 쪽으로 기우는 것 같네요.
위의 이슈 역시 중요하지만 단위에 대해 확실히 정해놓고 가는 것이 좋을 것 같습니다.
제가 알기론 premium과 deposit은 wei로 정해졌지만 price는 잘 모르겠네요.
btc/usdt로 알고 있으면 될까요?

**Comment by atoye1** [comment]
체인링크 오라클을 사용한다면 btc/usdt를 사용하는게 맞지 않을까 합니다.
아마도 체인링크에서 eth/usdt 데이터를 받아와서 두 값을 활용해 btc/eth를 계산하면 되지 않을까 하는 `추측`이 듭니다.

**Comment by Duhoon** [comment]
현재는 initialPrice도 Buyer가 임의로 작성하게 만들었습니다.
이를테면 premium 과 deposit은 wei단위로 넘어가게 되어 있는데

initialPrice 같은 경우는 9000 으로 입력한다면 9000wei/(btc 1개)라고 생각하시면 될 것 같습니다.
그렇다면 numOfAsset이 1개로 입력되면, 전체 자산 가격은 9000wei가 될테고
numOfAsset이 10개로 입력되면, 전체 자산 가격은 90000wei가 될겁니다.

claimPrice 는 initialPrice가 9000이니 이 가격 이하로 범위가 설정될 것이고
예시로 7000을 입력하도록 하겠습니다.
그럼 claimPrice는 7000wei/(btc 1개)로 산정될 겁니다.
그럼 체인링크 오라클 가격이든, 목업 가격이든 7000이하로 btc 가격이 떨어졌을 때
btc 1개당 (initialPrice - claimPrice) 만큼 보상금이 책정될 겁니다.
numOfAsset이 10개면 ( initialPrice - claimPrice ) * 10 으로 계산하면 보상금을 구할 수 있을 겁니다.

**Comment by bbabi0901** [comment]
적용 완료되어 닫습니다
